version: "3.8"

services:
  app:
    image: todo-frontend
    environment:
      $HOSTNAME: app
      REACT_APP_BACKEND_URL: "http://localhost:3001"
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: todo-frontend
    networks:
      - todo
networks:
  todo:
    name: todo
